wallpaper = {
    {
        monitor = "DP-2",
        path = "/home/sumit/Downloads/rick.png",
        fit_mode = "cover",
    },
    {
        monitor = "",
        path = "/home/sumit/Downloads/rick.png",
        fit_mode = "cover",
    },
}
